#!/usr/bin/env python3
"""Generate the GCE hardware-event -> CMDQ_EVENT_ENUM lookup used by the
ioctl interposer.

The API 25 libdpframework passes *raw GCE hardware event values* in
op_meta.event, because that is what its own vintage of the MDP interface
took. This kernel's mdp_ioctl_ex meta ABI instead expects a
CMDQ_EVENT_ENUM *index*, which cmdq_op_wait() translates to a hardware
value through the DTS-populated event table. Feeding it a hardware value
therefore either lands on an unrelated event or, far more often, on an
enum with no DTS entry at all - whose table slot defaults to a negative
number, so cmdq_op_wait() returns -EINVAL and the entire submit is
rejected.

The map is built by composing the kernel's own two sources:

    cmdq_event_common.h : DECLARE_CMDQ_EVENT(NAME, enum_index, dts_name)
    mt8163.dtsi         : dts_name = <hardware_value>

giving hardware_value -> enum_index, which is exactly the inverse of what
cmdq_core_get_event_value() does at runtime.
"""

import re
import sys
from pathlib import Path

KERNEL = Path(sys.argv[1] if len(sys.argv) > 1
              else "/mnt/dev/lineage-18.1/kernel/amazon/mt8163-4.9")
HDR = KERNEL / "drivers/misc/mediatek/cmdq/v2/cmdq_event_common.h"
DTSI = KERNEL / "arch/arm64/boot/dts/mediatek/mt8163.dtsi"

# DECLARE_CMDQ_EVENT(CMDQ_EVENT_MDP_RDMA0_EOF, 52, mdp_rdma0_frame_done)
decl = re.compile(r"DECLARE_CMDQ_EVENT\(\s*(\w+)\s*,\s*\(?(-?\d+)\)?\s*,\s*(\w+)\s*\)")
# mdp_rdma0_frame_done = <28>;
prop = re.compile(r"^\s*(\w+)\s*=\s*<\s*(\d+)\s*>\s*;")

enum_by_dts = {}
name_by_enum = {}
for m in decl.finditer(HDR.read_text()):
    name, idx, dts = m.group(1), int(m.group(2)), m.group(3)
    if idx < 0:
        continue
    enum_by_dts.setdefault(dts, idx)
    name_by_enum[idx] = name

hw_by_dts = {}
for line in DTSI.read_text().splitlines():
    m = prop.match(line)
    if m:
        hw_by_dts.setdefault(m.group(1), int(m.group(2)))

# hardware value -> enum index. Several dts names can share a hardware
# value (isp_frame_done_a and isp_frame_done_p2_0 are both 131); the first
# one that resolves to a known enum wins.
hw_to_enum = {}
for dts, hw in sorted(hw_by_dts.items()):
    idx = enum_by_dts.get(dts)
    if idx is None or hw in hw_to_enum:
        continue
    hw_to_enum[hw] = (idx, dts)

hi = max(hw_to_enum) if hw_to_enum else 0
out = ["/* Generated by gen_event_map.py - do not edit. */",
       "/* GCE hardware event value -> CMDQ_EVENT_ENUM index. */",
       "",
       "#define EVENT_MAP_MAX %d" % (hi + 1),
       "",
       "static const short event_map[EVENT_MAP_MAX] = {"]
for hw in range(hi + 1):
    if hw in hw_to_enum:
        idx, dts = hw_to_enum[hw]
        out.append("\t[%d] = %d,\t/* %s */" % (hw, idx, dts))
    else:
        out.append("\t[%d] = -1," % hw)
out += ["};", ""]

dest = Path(__file__).with_name("event_map.h")
dest.write_text("\n".join(out) + "\n")

print("wrote %s (%d hardware events mapped)" % (dest, len(hw_to_enum)))
for hw in (28, 32, 33, 131):
    if hw in hw_to_enum:
        idx, dts = hw_to_enum[hw]
        print("  hw %-4d -> enum %-4d %s (%s)" % (hw, idx, name_by_enum.get(idx, "?"), dts))
